<a href="https://colab.research.google.com/github/UznetDev/Data-science-home-work/blob/main/20_Sen_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import *
from sklearn.linear_model import *
from sklearn.metrics import *
from sklearn.datasets import load_breast_cancer
import warnings
warnings.filterwarnings('ignore')

In [11]:
# Load the dataset
data = load_breast_cancer()

# Features and target variable
X = data.data
y = data.target  # Target: 0 = malignant, 1 = benign

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
X.shape, y.shape

((569, 30), (569,))

In [17]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [18]:
y_pred = model.predict(X_test)

In [19]:
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0])

In [21]:
y_prob = model.predict_proba(X_test)[:, 1]

In [22]:
y_prob

array([8.85965913e-01, 1.08546708e-08, 7.15624834e-03, 9.95355358e-01,
       9.98358034e-01, 1.00096259e-09, 2.47385914e-12, 5.14865588e-03,
       9.95333126e-01, 9.77141748e-01, 9.59474766e-01, 4.71496245e-04,
       9.84347684e-01, 4.98989674e-01, 9.93203255e-01, 1.14066179e-03,
       9.94679659e-01, 9.99717446e-01, 9.95267315e-01, 4.49021842e-07,
       8.28942312e-01, 9.65374730e-01, 7.60533594e-09, 9.94860302e-01,
       9.91069907e-01, 9.98917417e-01, 9.94424116e-01, 9.96547500e-01,
       9.91672591e-01, 1.40724096e-07, 9.96438693e-01, 9.96883729e-01,
       9.81974005e-01, 9.83093111e-01, 9.97993944e-01, 9.96795978e-01,
       3.26373368e-03, 9.85961034e-01, 5.34511638e-06, 9.22444806e-01,
       9.98090186e-01, 3.00695145e-03, 9.98874069e-01, 9.89859483e-01,
       9.98068568e-01, 9.59817531e-01, 9.98211777e-01, 9.92502162e-01,
       9.27669611e-01, 9.94407033e-01, 1.84043812e-04, 4.40756182e-09,
       9.51296108e-01, 9.96893013e-01, 9.98787284e-01, 9.80248531e-01,
      

In [26]:
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)
ps = precision_score(y_test, y_pred)
rs = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_prob)
ls = log_loss(y_test, y_prob)

In [27]:
print("Confusion Matrix:\n", cm)
print("Accuracy:", ac)
print("Precision:", ps)
print("Recall:", rs)
print("F1 Score:", f1)
print("ROC AUC Score:", roc_auc)
print('Log Loss: ', ls)

Confusion Matrix:
 [[40  3]
 [ 1 70]]
Accuracy: 0.9649122807017544
Precision: 0.958904109589041
Recall: 0.9859154929577465
F1 Score: 0.9722222222222222
ROC AUC Score: 0.9970520799213888
Log Loss:  0.08236634299066128
