<a href="https://colab.research.google.com/github/UznetDev/Data-science-home-work/blob/main/MATH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
from sklearn.preprocessing import StandardScaler

In [14]:
v = [3, 6, 8, 5, 7]
c = [7, 4, 9, 5, 3]

In [15]:
mean_v = np.mean(v)
std_v_n1 = np.std(v, ddof=1)

mean_c = np.mean(c)
std_c_n1 = np.std(c, ddof=1)

In [16]:
standard_v = (v - mean_v) / std_v_n1
standard_c = (c - mean_c) / std_c_n1

In [17]:
standard_data = np.array([standard_v, standard_c])
covariance_matrix = np.cov(standard_data)
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)
eigen_values, eigen_vectors

(array([0.96762003, 1.03237997]),
 array([[-0.70710678, -0.70710678],
        [ 0.70710678, -0.70710678]]))

In [21]:
sorted_index = np.argsort(eigen_values)[::-1]
sorted_eigenvalue = eigen_values[sorted_index]
sorted_eigenvectors = eigen_vectors[:,sorted_index]
transformed_data = standard_data.T @ sorted_eigenvectors
transformed_data

array([[ 0.61824632,  1.44035462],
       [ 0.39625471, -0.54329764],
       [-1.80701046,  0.18953829],
       [ 0.47025191,  0.11791978],
       [ 0.32225751, -1.20451506]])